spring:
  application:
    name: servicio-eureka-server
#puerto por defecto
server: 
  port: 8761
#Eureka se registra como cliente
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false